name: sync

on:
  schedule:
  - cron: '5/15 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Sync with upstream
    - uses: actions/checkout@v2
    - uses: shitiomatic/forkbacon@master
      with:
        upstream_url: "https://github.com/ecamp/dummy.git"
        upstream_branch: "devel"
        branch: "devel"
        method: "rebase"
